name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser
          pip install xvfbwrapper

      - name: Start xvfb
        run: |
          sudo Xvfb :99 -ac -screen 0 1024x768x8 &
          export DISPLAY=:99

      - name: Run Python script with xvfb
        run: xvfb-run -a python widget_test.py
